---
project_name: hilo

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/hilod
    id: "hilod"
    binary: hilod
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -tags=netgo ledger
      - -trimpath
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X github.com/cosmos/cosmos-sdk/version.Name=hilo -X github.com/cosmos/cosmos-sdk/version.AppName=hilod -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }} -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }} -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger -X github.com/tendermint/tendermint/version.TMCoreSemVer={{ .Env.TM_VERSION }}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: cicizeo
    name: hilo
  name_template: "{{.Version}} Release Notes"

checksum:
  name_template: SHA256SUMS-{{.Version}}.txt
  algorithm: sha256

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

changelog:
  skip: true
