version: "3"

services:
  hilodnode0:
    container_name: hilodnode0
    image: "hilonetwork/hilod-localnet"
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
    environment:
      - ID=0
    volumes:
      - ./build:/hilod:Z
    networks:
      localnet:
        ipv4_address: 192.168.30.2

  hilodnode1:
    container_name: hilodnode1
    image: "hilonetwork/hilod-localnet"
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
    environment:
      - ID=1
    volumes:
      - ./build:/hilod:Z
    networks:
      localnet:
        ipv4_address: 192.168.30.3

  hilodnode2:
    container_name: hilodnode2
    image: "hilonetwork/hilod-localnet"
    ports:
      - "26676-26677:26656-26657"
      - "1319:1317"
      - "9092:9090"
    environment:
      - ID=2
    volumes:
      - ./build:/hilod:Z
    networks:
      localnet:
        ipv4_address: 192.168.30.4

  hilodnode3:
    container_name: hilodnode3
    image: "hilonetwork/hilod-localnet"
    ports:
      - "26686-26687:26656-26657"
      - "1320:1317"
      - "9093:9090"
    environment:
      - ID=3
    volumes:
      - ./build:/hilod:Z
    networks:
      localnet:
        ipv4_address: 192.168.30.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.30.0/25
